apiVersion: v1
kind: ServiceAccount
metadata:
  name: danm-installer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caas:danm-installer
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: [ "*" ]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - "*"
  resources:
  - serviceaccounts
  verbs:
  - create
  - get
  - patch
- apiGroups:
  - "*"
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - danm.k8s.io
  resources:
  - clusternetworks
  - danmeps
  - danmnets
  - tenantnetworks
  - tenantconfigs
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - daemonsets
  - deployments
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - delete
  - get
  - create
  - update
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
  - get
  - update
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - update
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caas:danm-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caas:danm-installer
subjects:
- kind: ServiceAccount
  name: danm-installer
  namespace: kube-system
